### PR TITLE
fix #18 provenance graph menu

### LINKED ISSUE #18: Add login and provenance menu to header
In the CLUE Gapminder we had a login and provenance menu where we could manage persistent provenance graphs. I need this functionality to upload the Rosling stories as persistent provenance graph.

image

@sgratzl Could you please take care of this and add/activate the necessary lines?

### PR DESCRIPTION
**Pull request by sgratzl**

### CODE REVIEW

**Comment by thinkh** [comment]
@sgratzl Thanks for your implementation. I have a few issues with it:

## 1. Mandatory login instead of optional

When I open the app in the browser, I'm prompted for the password every time. I would expect an behavior as in the old Gapminder where the login is optional and by default a temporary session is created.

gapminder-login

## 2. I cannot logout once I'm logged in...

gapminder-logout

## 3. Images are not generated

I tried this for a remote provenance graph and got the following Docker log: 

```
util_chrome_1   | [0330/093846.895492:ERROR:http_server.cc(415)] Cannot handle request with protocol: "�1  JJ�+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093847.356469:ERROR:http_server.cc(415)] Cannot handle request with protocol: �Z6��i)l�?  ZZ�+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093848.481543:ERROR:http_server.cc(415)] Cannot handle request with protocol: =�n�X@`U,\��C  �+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093852.165357:ERROR:http_server.cc(415)] Cannot handle request with protocol: �v
util_chrome_1   | [0330/093854.675378:ERROR:http_server.cc(415)] Cannot handle request with protocol: ��(��!d4e��a�i@^�w  �+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093858.553082:ERROR:http_server.cc(415)] Cannot handle request with protocol: 7�A/%j}݁P�[d�S��  ���+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093859.724401:ERROR:http_server.cc(415)] Cannot handle request with protocol: �
util_chrome_1   | [0330/093900.387655:ERROR:http_server.cc(415)] Cannot handle request with protocol: 酿�j�<��
util_chrome_1   | [0330/093902.221283:ERROR:http_server.cc(415)] Cannot handle request with protocol: ta%^  ���+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093903.903223:ERROR:http_server.cc(415)] Cannot handle request with protocol: ��K  ���+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093906.203550:ERROR:http_server.cc(415)] Cannot handle request with protocol: ����,fv��  **�+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093908.244715:ERROR:http_server.cc(415)] Cannot handle request with protocol: /vς��"ܻI=  ���+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093914.822843:ERROR:http_server.cc(415)] Cannot handle request with protocol: "]������~�  ���+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093919.467874:ERROR:http_server.cc(415)] Cannot handle request with protocol: R<�o�W�^�  �+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093920.996773:ERROR:http_server.cc(415)] Cannot handle request with protocol: T���&99���B�)<�G��>
util_chrome_1   | [0330/093921.558908:ERROR:http_server.cc(415)] Cannot handle request with protocol: 1��Y\l �����  �+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093923.244733:ERROR:http_server.cc(415)] Cannot handle request with protocol: ~h5�3+
util_chrome_1   | [0330/093925.548933:ERROR:http_server.cc(415)] Cannot handle request with protocol: a���U����]��[�}~�  ���+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093926.956825:ERROR:http_server.cc(415)] Cannot handle request with protocol: GK���  ���+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093927.367820:ERROR:http_server.cc(415)] Cannot handle request with protocol: g��o�>gw<���,֎+]�Ԣ3  
util_chrome_1   | [0330/093930.846256:ERROR:http_server.cc(415)] Cannot handle request with protocol: ��+.B�a�/�)  �+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093931.718756:ERROR:http_server.cc(415)] Cannot handle request with protocol: �AK�z�Ä��k/v����gi�2�5  �+�/�,�0̨̩�� � � / 5
util_chrome_1   | [0330/093934.322342:ERROR:http_server.cc(415)] Cannot handle request with protocol: ��Z  
util_chrome_1   | [0330/093937.790230:ERROR:http_server.cc(415)] Cannot handle request with protocol: W�0^�
util_chrome_1   | [0330/093939.982413:ERROR:http_server.cc(415)] Cannot handle request with protocol: ��#_ȼ�wF<���  
util_chrome_1   | [0330/093944.218887:ERROR:http_server.cc(415)] Cannot handle request with protocol: �  ���+�/�,�0̨̩�� � � / 5
api_1           | Traceback (most recent call last):
api_1           |   File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 884, in handle_one_response
api_1           |     self.run_application()
api_1           |   File "/usr/local/lib/python2.7/site-packages/geventwebsocket/handler.py", line 88, in run_application
api_1           |     return super(WebSocketHandler, self).run_application()
api_1           |   File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 870, in run_application
api_1           |     self.result = self.application(self.environ, self.start_response)
api_1           |   File "/usr/local/lib/python2.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
api_1           |     return self.app(environ, start_response)
api_1           |   File "phovea_server/phovea_server/dispatcher.py", line 63, in __call__
api_1           |     return app(environ, start_response)
api_1           |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
api_1           |     return self.wsgi_app(environ, start_response)
api_1           |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
api_1           |     response = self.make_response(self.handle_exception(e))
api_1           |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
api_1           |     reraise(exc_type, exc_value, tb)
api_1           |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
api_1           |     response = self.full_dispatch_request()
api_1           |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
api_1           |     rv = self.handle_user_exception(e)
api_1           |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
api_1           |     reraise(exc_type, exc_value, tb)
api_1           |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
api_1           |     rv = self.dispatch_request()
api_1           |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
api_1           |     return self.view_functions[rule.endpoint](**req.view_args)
api_1           |   File "/phovea/phovea_clue/phovea_clue/remoteplayer.py", line 190, in create_thumbnail
api_1           |     s = _create_screenshot_impl(app, prov_id, state, force=force)
api_1           |   File "/phovea/phovea_clue/phovea_clue/remoteplayer.py", line 132, in _create_screenshot_impl
api_1           |     obj = create_via_selenium(url)
api_1           |   File "/phovea/phovea_clue/phovea_clue/remoteplayer.py", line 121, in create_via_selenium
api_1           |     return screenshotter.take(url, eval_clue)
api_1           |   File "/phovea/phovea_clue/phovea_clue/remoteplayer.py", line 55, in take
api_1           |     driver = self._get()
api_1           |   File "/phovea/phovea_clue/phovea_clue/remoteplayer.py", line 44, in _get
api_1           |     self._driver = webdriver.Chrome(chrome_options=options)
api_1           |   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
api_1           |     desired_capabilities=desired_capabilities)
api_1           |   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
api_1           |     self.start_session(desired_capabilities, browser_profile)
api_1           |   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 188, in start_session
api_1           |     response = self.execute(Command.NEW_SESSION, parameters)
api_1           |   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
api_1           |     self.error_handler.check_response(response)
api_1           |   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
api_1           |     raise exception_class(message, screen, stacktrace)
api_1           | WebDriverException: Message: unknown error: cannot connect to chrome at chrome:9222
api_1           | from chrome not reachable
api_1           |   (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.9.87-linuxkit-aufs x86_64)
api_1           |
api_1           | {'GATEWAY_INTERFACE': 'CGI/1.1',
api_1           |  'HTTP_ACCEPT': 'image/webp,image/apng,image/*,*/*;q=0.8',
api_1           |  'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
api_1           |  'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9',
api_1           |  'HTTP_CACHE_CONTROL': 'no-cache',
api_1           |  'HTTP_CONNECTION': 'close',
api_1           |  'HTTP_COOKIE': 'remember_token=nostalgic_pike|f6199efc055524f97fdb5268b8d1665558be84ac7556232ee048a1bd4bcb6c37a4ac1728bd71e087e52660f1769e2
i1zlIGp8GOQv57Radvebz3PeF0mYfbCOXvfB82cHJnKJ_w9g0l8OEjsJicolpUzhPraqtkdOpAK-t26XQ_kbCQZY_1cVVxWlDQUWzSUkbWZKybjPSxoLwX1D-xq80WAzolVZE8EW376KwpVOyFa7OirhLT7Drt
api_1           |  'HTTP_HOST': 'localhost:8080',
api_1           |  'HTTP_PRAGMA': 'no-cache',
api_1           |  'HTTP_REFERER': 'http://localhost:8080/',
api_1           |  'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.66 Safari/537.36',
api_1           |  'PATH_INFO': '/thumbnail/vega/persistentWs6Gftw/7.jpg',
api_1           |  'QUERY_STRING': 'width=128',
api_1           |  'REMOTE_ADDR': '172.23.0.1',
api_1           |  'REMOTE_PORT': '45440',
api_1           |  'REQUEST_METHOD': 'GET',
api_1           |  'SCRIPT_NAME': '/api/clue',
api_1           |  'SERVER_NAME': '1c628c9b0a4b',
api_1           |  'SERVER_PORT': '80',
api_1           |  'SERVER_PROTOCOL': 'HTTP/1.1',
api_1           |  'SERVER_SOFTWARE': 'gevent/1.1 Python/2.7',
api_1           |  'werkzeug.proxy_fix.orig_http_host': 'localhost:8080',
api_1           |  'werkzeug.proxy_fix.orig_remote_addr': '172.23.0.1',
api_1           |  'werkzeug.proxy_fix.orig_wsgi_url_scheme': 'http',
api_1           |  'werkzeug.request': <Request 'http://localhost:8080/api/clue/thumbnail/vega/persistentWs6Gftw/7.jpg?width=128' [GET]>,
api_1           |  'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f9c536f11e0>,
api_1           |  'wsgi.input': <gevent.pywsgi.Input object at 0x7f9c3904f738>,
api_1           |  'wsgi.multiprocess': False,
api_1           |  'wsgi.multithread': False,
api_1           |  'wsgi.run_once': False,
api_1           |  'wsgi.url_scheme': 'http',
api_1           |  'wsgi.version': (1, 0)} failed with WebDriverException
api_1           |
```

**Comment by sgratzl** [comment]
1 and 2 are fixed. 

regarding 3 as mentioned in #19 the chrome debugger connection is broken. took me another two hours to downgrade to chrome 61 to get the following picture: 

image


re config hint: see phovea_clue/phovea_clue/config.json

**Comment by thinkh** [comment]
@sgratzl Thanks for your fixes and your time!

I updated my setup, but I can't generate thumbnails.

1. Created a fresh workspace with `yo phovea:setup-workspace vega_clue_product` (switch to this branch)
2. `npm run:watch:vega_clue`
3. `docker-compose up`
4. Open http://localhost:9000/vega_clue/
5. Create/Load persistent session
6. Search for something
7. Thumbnails are only white

This is the server log I get:

```
api_1           | configuration file: /phovea/config.json
api_1           | 15:39:55 INFO phovea_server.server: init application: <Flask 'phovea_server.mainapp'>
api_1           | 15:39:55 INFO phovea_security_flask.flask_login_impl: using dummy store
api_1           | add application: caleydo-clue-screenshot at namespace: /api/clue
api_1           | add application: caleydo-dataset at namespace: /api/dataset
api_1           | add application: caleydo-idtype at namespace: /api/idtype
api_1           | 15:40:02 INFO phovea_server.server: init application: <Flask 'phovea_clue.remoteplayer'>
api_1           | 15:40:02 INFO phovea_clue.remoteplayer: requesting url http://web/?clue_random=nullo#clue_graph=persistentWsHunt5&clue_state=187&clue=P&clue_store=remote&clue_headless=Y
api_1           | 15:40:02 INFO phovea_clue.remoteplayer: create driver
api_1           | 15:40:04 INFO phovea_clue.remoteplayer: url http://web/?clue_random=nullo#clue_graph=persistentWsHunt5&clue_state=187&clue=P&clue_store=remote&clue_headless=Y
api_1           | 15:40:34 ERROR phovea_clue.remoteplayer: cannot fullfil query Message: no such element: Unable to locate element: {"method":"css selector","selector":"main"}
api_1           |   (Session info: headless chrome=61.0.3163.100)
api_1           |   (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.9.87-linuxkit-aufs x86_64)
api_1           | Traceback (most recent call last):
api_1           |   File "/phovea/phovea_clue/phovea_clue/remoteplayer.py", line 61, in take
api_1           |     body(driver)
api_1           |   File "/phovea/phovea_clue/phovea_clue/remoteplayer.py", line 107, in eval_clue
api_1           |     driver.find_element_by_css_selector('main')
api_1           |   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 589, in find_element_by_css_selector
api_1           |     return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
api_1           |   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 955, in find_element
api_1           |     'value': value})['value']
api_1           |   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
api_1           |     self.error_handler.check_response(response)
api_1           |   File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
api_1           |     raise exception_class(message, screen, stacktrace)
api_1           | NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"main"}
api_1           |   (Session info: headless chrome=61.0.3163.100)
api_1           |   (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.9.87-linuxkit-aufs x86_64)
api_1           |
api_1           | 15:40:34 INFO phovea_clue.remoteplayer: take screenshot
```

**Comment by thinkh** [comment]
I also played around with other CSS selectors, but I always get the same message. So I don't know what else I have to do in order to get the thumbnails running. If it won't work soon, I will just do the video and without thumbnails. 😐

**Comment by thinkh** [comment]
And btw. if I open the URL from the server log in the browser (http://localhost:9000/vega_clue/?clue_random=nullo#clue_graph=persistentWsHunt5&clue_state=187&clue=P&clue_store=remote&clue_headless=Y) I get a pretty nice visualization...

image

**Comment by sgratzl** [comment]
how does your `config.json` looks like?

**Comment by thinkh** [comment]
It's still the default one from the repository. I haven't touched the file.

```json
{
  "server": "http://web",
  "server__local": "http://api/vega_clue", // and use npm run watch:<app>... to launch the application and access it via http://localhost:9000/<app>
  "chromeAddress": "chrome:9222",
  "memcached": [
    "memcached:11211"
  ]
}
```

**Comment by sgratzl** [comment]
well change your local config to: 
```
{
  "phovea_clue": {
   "server": "http://api/vega_clue"
  }
}
```

I mean the one in your workspace

**Comment by thinkh** [comment]
Aha... now I get it! It was not really obvious what I should do. Thanks, now it's working! 🎉 

image

**Pull request merged**
